### ISSUE TITLE
new svg preview bug!

### ISSUE THREAD

**Issue by crtgirl** [olafmoriarty/blue-bots-done-quick#19]
okay so it looks like href images in my code are working flawlessly, butttt somehow the text that gets written over them is rendering over the code box outside of the preview now! no idea how that is happening, and i don't know if it's going to effect the output because i haven't tweaked my <text> code enough yet.
examples:
![image](https://github.com/user-attachments/assets/9bd1960b-cc0a-4c62-a3a6-11aadb53826c)

**Comment by crtgirl** [comment]
okay so it looks like whatever is happening here is related to the "style=position: absolute; left: 50%; top:50%;" string in my svg code. adjusting the percentages there adjusts where that text is appearing relative to the top corner of the page, instead of the top corner of the svg preview. 

the text isn't appearing in the posts on bsky but i still dont know if thats just a problem with my code yet. more exploring to be done!

**Comment by olafmoriarty** [comment]
Hi,

as far as I can tell, your code appears to contain some tags and styles that aren't part of SVG. Those tags and styles need to be wrapped inside a `<foreignObject>` tag to work, and since that tag is not supported in the library I'm using to convert SVGs to PNGs, you can't really use them here.

I haven't used SVGs enough myself to give you professional advice on how to solve this, but for a start I'd suggest removing the `<p>` and using the `x` and `y` attributes of `<text>` instead of CSS positioning, like this:

    "need_with_image": ["#first# {svg <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" width=\"800\" height=\"600\" style=\"position: relative;\"><image x=\"0\" y=\"0\" width=\"800\" height=\"600\" xlink:href=\"https://raw.githubusercontent.com/mxquinn/shaxxvibecheck/master/maslow_1.png\" /><text  width=\"800\" height=\"600\" x=\"400\" y=\"300\" text-anchor=\"middle\" style=\"font-size: 25px;\">#first#</text></svg>}"],

That line displays the text both in the preview and in the bsky posts, but it's not perfect: SVG does not appear to have a way to automatically wrap text over multiple lines (I get the impression that one suggested way of doing this is using `<tspan>` tags and positioning these relative to each other using `dy`, which is... pretty complicated when the text in question is auto-generated), so it may not be what you're after.

Unfortunately I have no better solution to offer at the moment. Pure SVG does not support HTML, and it has a different set of valid CSS attributes than HTML has, so code must be built with that in mind to work here.

**Comment by olafmoriarty** [comment]
I see that the bot is working now, so I'm closing this issue.
