### ISSUE TITLE
feature request: alt text preview (plus comments on SVG preview vs post)

### ISSUE THREAD

**Issue by alien-sunset** [olafmoriarty/blue-bots-done-quick#21]
hiya, so part of my new socks bot (https://bsky.app/profile/socksbot.bsky.social) is the the alt text is also generated via the tracery, but on the bot preview page I can't see that.

I do most of my tracery coding and checking in VSCode so it doesn't super impact me, but for other people it may be handy to be able to confirm that tracery produced alt text comes out properly before it starts posting.

semi relatedly, you stated previously that you use different methods to produce the preview images vs the posting images, is there a particular reason for this?
i have notice that there is a bit of discrepancy between the appearance of the outputs which does require tweaking after the bot has started posting to ensure that the images are displaying properly on BSky.

for instance, here is the preview image for (@grandmas-quilt.bsky.social) vs how it actually appears on BSky:

![grandmassvgprevBBDQ](https://github.com/user-attachments/assets/fd63c67f-e110-44ed-bd8a-cee867be0eeb)
![bafkreifarnb5cksr42fzt53gsnr4d2uftpyvv5zl2ltgoxsa5hvdtpceyu](https://github.com/user-attachments/assets/61ce0cb3-d042-489f-a0bf-f1f496cc1fd9)

relatedly-relatedly (this part is mostly just me thinking aloud and not necessarily a request or anything)
CBTS has a similar issue of preview vs post.
but on CBTS it just displays the actual SVG, which is super helpful in that if i notice an issue i can inspect the page element to see the generated SVG code to see where any breaks or oddities may be happening.
like I said earlier, I do most of my coding in VSCode, so it's not a big issue, but i am recently running into an issue where CBTS is processing the tracery differently (it's using a slightly older version) so being able to look to see where and how it's breaking is handy in troubleshooting.  this may also be handy or at least a thing to think about with regards to BBDQ as you are technically using a different version of tracery to me as well.

OH! and!
on CBTS you can re-roll the tracery to see more results to double check all the bits, on BBDQ there's no way to re-rell unless you actually make an edit to the code - reloading the page just logs you out and brings you back to the homepage.
(on CBTS there's a little "reload" button next to the preview you can click to get it to run the code again. on BB I've just been adding spaces to the code, but because of the preview window placement in relation to the edit window i have to scroll up, space, scroll down, scroll up, space, scroll down, etc....(and then I have to remember to erase all the extra spaces))

anyways, sorry for being so rambly 😅

**Comment by olafmoriarty** [comment]
Adding alt text is an easy fix, and I'm working on a bigger frontend change now anyway, so I'll include it before the next time I run a build on it. The alt text is actually already added to the image if you use the `{svg <svg></svg> Alt-text}` format, but adding it when you use the `{alt}` format was a bit more complicated, so I decided to handle that problem later. Still, just displaying the alt text on-screen under the images where you can easily see it would probably be the preferred solution, so I'll probably just add that.

The thing about the SVG previews is that they're not actually previews at all - they are, indeed, SVGs. The only thing I do with them before displaying them in the browser is converting them to base64 so that I can put the data inside an `<img>` tag. The reason I chose to put the SVG inside an `<img>` tag instead of just using the `<svg>` is simply because that made it easier to resize the images and, ironically, add alt text. And there's an exception - if the SVG contains an image with an `xlink:href` reference to an external image, the SVG *will* actually be displayed on screen (or a sanitized version of it) because converting that to a data url would be a very much more difficult process. Anyway, I figured that as long as your browser supports SVG, there's not really a reason to jump through a lot of hoops to convert it when it works out of the box.

Grandma's quilt uses `<text>`, right? It could be a possibility that the SVG shown on the website somehow inherits the font used elsewhere on the site. While I can't guarantee it will work, I'll try setting the font on the SVG container to initial and see what happens.

Honestly, SVGs was an afterthought here. I didn't need it, my friends didn't need it, so I figured it was probably not something a lot of people would use. Clearly I was wrong about that. But a lot of the SVG issues can be boiled down to the fact that I don't entirely know what I'm doing, so I'm trying to find the simplest solutions possible to making it work and then make up solutions to all the bugs that pop up as I go. Fortunately, I get the impression that most people who use SVGs know enough about how to build them to avoid the biggest issues.

What are the differences between this Tracery version and the one CBTS uses? What exactly works differently?

A reload button would definitely be nice, I just haven't gotten around to it. Putting it on the to-do-list.

**Comment by alien-sunset** [comment]
heh i'm actually in the middle of a bug issue with BooDoo over some weirdness I'm experiencing the CBTS's tracery as, my thing is working perfectly in VSCode/node.js, and here, but for some reason is reading things in the wrong order (?) on CBTS

all I know is that CBTS uses the JS tracery and that you are using a PHP port (if i'm understanding properly) and that that can result in odd little discrepancies occasionally 


also, to be fair, the HUGE majority of tracery based bots have no use for svg but there's a small niche group of weirdos (i'm including myself here) who enjoy pushing the boundaries of what can be accomplished with seemingly very simple code. 
(for ex, the inspirations for both Alien's Aliens and socksBot were much more "complicated" JS codes, and the canvas feature, and I wanted to see if I could simplify it all down to work in tracery/SVG instead  (in some ways I actually find SVG (and CSS <div>) easier to work with than with the js canvas, but I've been told that I'm quite odd)
