### ISSUE TITLE
label tag not working?

### ISSUE THREAD

**Issue by alien-sunset** [olafmoriarty/blue-bots-done-quick#32]
i notice that a post made by Remedios_Varo_bot was not labeled, despite having {label nudity} in the code and ended up getting tagged by the moderators.

https://bsky.app/profile/remedios-varo-bot.bsky.social/post/3le7epmszep27

did I place it wrong?

also, another possible tagging issue, one on the images alt text didn't fully go through:
https://bsky.app/profile/remedios-varo-bot.bsky.social/post/3le4ub42fa72c

**Comment by olafmoriarty** [comment]
Hmm, from what I can see in the post record, that post *was* correctly self-labeled nudity?

**Comment by alien-sunset** [comment]
it showed up as unlabeled when I saw it, and by the time I got around to making this report it says it was labeled by moderators, not self labeled.

and I labeled it as "nudity", not "explicit sexual content" (which is IS NOT)
![image](https://github.com/user-attachments/assets/695ca580-368e-4c79-86a9-cc25f0f55dda)

**Comment by olafmoriarty** [comment]
And the account you saw it from is NOT set to show nudity? Because if it is, I don't think the label is visible on bsky, even though it's still there.

**Comment by alien-sunset** [comment]
on my personal account, adult content is enabled, but everything is set to "hide"
on Remedios, adult contend is not enabled.

either way I was able to see it BEFORE the moderation team labeled it, (both on my account and from Remedios's account) and now it is labeled as a stronger form of content than it actually is/was marked as and It is hidden behind the label for both.

**Comment by alien-sunset** [comment]
this is how the post SHOULD have looked to me:
![image](https://github.com/user-attachments/assets/77c57eaa-8e80-4b2f-8e56-0ff9191563bc)
(notice the "labeled by the author" note)

it WAS perfectly visible, but now this is how it looks:
![image](https://github.com/user-attachments/assets/45b24b9e-b650-4895-a0f3-98487684970f)
(notice the "labeled by bluesky moderation services" note)

**Comment by olafmoriarty** [comment]
But according to the post record itself, which I have now double-checked multiple times, the label WAS always there.

![image](https://github.com/user-attachments/assets/c285bfac-ef92-4c9a-8fa6-f12efcb5928f)

This is the label part of the JSON that Bluesky loads when showing you the bot, which clearly states that
- The `nudity` label was added to the post the same millisecond it was posted
- The account that added the `nudity` label was Remedios Varo Bot
- The `porn` label was added to the post three minutes later, most likely in an automated process and not because somebody reported it
- The account that added the `porn` label was Bluesky Moderation Service

So to me, everything looks like it has worked exactly as intended (except for the agressive moderation from Bluesky, but there's not anything I can do to override that)

**Comment by alien-sunset** [comment]
huh, yeah, ok, it was early in the morning so goodness knows what I was seeing.
still annoyed about the overzealous moderation tho, but we can't really do anything about that.

**Comment by olafmoriarty** [comment]
Well, you can appeal it, I think you get an Appeal  button if you click the label warning. I have no idea how effective that is.
